sudo: false
language: python
python:
{% for env in ['2.6', '2.7', '3.3', '3.4', '3.5', 'pypy'] %}
  - "{{ env }}"
{% endfor %}
env:
{% if cookiecutter.c_extension_support|lower == "yes" %}
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS="abrt segv"
{% endif %}
  matrix:
    - COVERAGE=cover
      {%- if cookiecutter.coveralls|lower == 'yes' %}
        {%- if cookiecutter.c_extension_support|lower == "yes" %},extension-coveralls{% endif %},coveralls
      {%- endif %}
      {%- if cookiecutter.codecov|lower == 'yes' %},codecov{% endif %}
    - COVERAGE=nocov
matrix:
  include:
    - python: "3.4"
      env: TOXENV=check

before_install:
  - easy_install --version
install:
  - pip install tox
  - virtualenv --version
  - tox --version

before_script:
  - export TOXENV=${TOXENV:-$TRAVIS_PYTHON_VERSION-$COVERAGE}
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

notifications:
  email:
    on_success: never
    on_failure: always
