language: python
python: '3.5'
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
{% for env in ['2.6', '2.7', '3.3', '3.4', '3.5', 'pypy'] %}
    - TOXENV={{ env }}-cover
      {%- if cookiecutter.coveralls|lower == 'yes' %}
        {%- if cookiecutter.c_extension_support|lower == "yes" %},extension-coveralls{% endif %},coveralls
      {%- endif %}
      {%- if cookiecutter.codecov|lower == 'yes' %},codecov{% endif %}
    - TOXENV={{ env }}-nocov
{% endfor %}
before_install:
  - easy_install --version
install:
  - pip install tox
  - virtualenv --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always

